sudo: required
services:
  - docker

before_install:
  - docker build -t guilhermefarias/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true guilhermefarias/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker" # é o nome do app -> frontend
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-971016326804"
  bucket_path: "docker" #same as app name
  on:
    branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"    